#!/bin/bash
set -euo pipefail

# Save third-party review tool output to a markdown file.
# Usage: save-review.sh <tool-name> <content>
#   tool-name: aikido | coderabbit | trivy
#   content: the review output (passed via stdin or as second argument)
#
# Output path: tools/third-party-reviews/<branch>/<tool>-<MM-DD-HH-MM>.md
#
# Examples:
#   echo "$FINDINGS" | .claude/scripts/save-review.sh aikido
#   .claude/scripts/save-review.sh coderabbit "$FINDINGS"

TOOL_NAME="${1:-}"
if [ -z "$TOOL_NAME" ]; then
    echo "Usage: save-review.sh <tool-name> [content]" >&2
    echo "  tool-name: aikido | coderabbit | trivy" >&2
    echo "  content: passed as arg or via stdin" >&2
    exit 1
fi

# Validate tool name
case "$TOOL_NAME" in
    aikido|coderabbit|trivy) ;;
    *)
        echo "ERROR: Unknown tool '$TOOL_NAME'. Must be: aikido, coderabbit, or trivy" >&2
        exit 1
        ;;
esac

# Read content from argument or stdin
if [ -n "${2:-}" ]; then
    CONTENT="$2"
else
    CONTENT=$(cat)
fi

if [ -z "$CONTENT" ]; then
    echo "ERROR: No content provided. Pass via argument or stdin." >&2
    exit 1
fi

# Get current git branch (sanitize for filename)
BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")
BRANCH_SAFE=$(echo "$BRANCH" | tr '/' '-' | tr ' ' '-')

# Timestamp with epoch seconds for uniqueness in parallel dispatch
TIMESTAMP=$(date +"%m-%d-%H-%M")
EPOCH=$(date +"%s")

# Capitalize tool name (portable, no bash-only ${var^})
TOOL_TITLE=$(echo "$TOOL_NAME" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

# Build output path — branch subdirectory groups reviews per epic/branch
OUTPUT_DIR="tools/third-party-reviews/${BRANCH_SAFE}"
FILENAME="${TOOL_NAME}-${TIMESTAMP}-${EPOCH}.md"
OUTPUT_PATH="${OUTPUT_DIR}/${FILENAME}"

# Create directory if needed
mkdir -p "$OUTPUT_DIR"

# Write the markdown file (use printf to avoid heredoc variable issues)
{
    printf '# %s Review Report\n\n' "$TOOL_TITLE"
    printf '**Tool:** %s\n' "$TOOL_NAME"
    printf '**Branch:** %s\n' "$BRANCH"
    printf '**Timestamp:** %s\n' "$(date +"%Y-%m-%d %H:%M %Z")"
    printf '**Generated by:** Claude Code automated review pipeline\n\n'
    printf '%s\n\n' '---'
    printf '%s\n' "$CONTENT"
} > "$OUTPUT_PATH"

# --- Option B: Verify the file was actually written ---
if [ ! -f "$OUTPUT_PATH" ]; then
    echo "SAVE_FAILED: File was not created at $OUTPUT_PATH" >&2
    exit 1
fi

FILE_SIZE=$(wc -c < "$OUTPUT_PATH" | tr -d ' ')
if [ "$FILE_SIZE" -lt 50 ]; then
    echo "SAVE_FAILED: File at $OUTPUT_PATH is suspiciously small (${FILE_SIZE} bytes)" >&2
    exit 1
fi

FILE_SIZE_HUMAN=$(awk "BEGIN {printf \"%.1fKB\", $FILE_SIZE/1024}")
echo "SAVED: $OUTPUT_PATH ($FILE_SIZE_HUMAN)"
